name: python unit tests 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: install deps 
        run: pip3 install pandas
      - name: unittest
        working-directory: UnitTest
        run: python3 -m unittest names.py
      - name: doctest
        working-directory: UnitTest 
        run: python3 -m doctest names.py
          
